kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbdemo
  namespace: pto
  labels:
    team: pto
  cluster: dev-fss
spec:
  image: docker.pkg.github.com/navikt/veilarbdemo/veilarbdemo:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://veilarbdemo.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
